name: CI Build and Upload Go Project
permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.21  # Specify the Go version

    # Step 3: Build the Go project
    - name: Build Go Project
      run: |
        cd go-app
        go build -o ../myapp

    # Step 4: Upload artifact to JFrog Artifactory
    - name: Upload to JFrog Artifactory
      env:
        ARTIFACTORY_URL: https://uhgsaaspoc.jfrog.io/artifactory
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
        ARTIFACTORY_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_PASSWORD }}
      run: |
        curl -u $ARTIFACTORY_USERNAME:$ARTIFACTORY_ACCESS_TOKEN \
          -T myapp \
          "$ARTIFACTORY_URL/go-uhg-go/myapp"