name: Go Build & Publish to Artifactory

on:
  push:
    branches: [ go-test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install dependencies
        working-directory: go-app
        run: go mod tidy

      - name: Build
        working-directory: go-app
        run: go build -o ../myapp

      - name: Test
        working-directory: go-app
        run: go test ./...

      - name: Install JFrog CLI
        run: |
          curl -fL https://getcli.jfrog.io | sh
          sudo mv jfrog /usr/local/bin/jf

      - name: Configure JFrog CLI
        env:
          ARTIFACTORY_URL: https://uhgsaaspoc.jfrog.io/artifactory
          ARTIFACTORY_USER: aashishgodse9867@gmail.com
          ARTIFACTORY_PASSWORD: cmVmdGtuOjAxOjE3ODc3MjQ4MzU6ZnJOcWx4MmRHVW5QcWdEQk0xRjhPSjBMWWFw
        run: |
          jf c add rt-server --artifactory-url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --password $ARTIFACTORY_PASSWORD --interactive=false

      - name: Publish to Artifactory
        run: |
          jf rt u myapp "go-app-test-local/myapp"